const TYRE_BRANDS = [
  "CEAT",
  "MRF",
  "Bridgestone",
  "Apollo",
  "JK",
  "Goodyear",
  "Michelin",
  "Yokohama",
  "Aeolus",
  "Pirelli",
  "Birla",
  "Continental",
  "Falken",
  "Kenda",
  "Maxxis",
  "Hankook",
  "Kumho",
  "Nexen",
  "Vredestein",
  "UltraMile",
  "Firestone",
  "Dunlop",
  "BKT",
  "Eurogrip",
  "Metro",
  "Metzeler",
  "Aramis",
  "Ralco",
];
const VEHICLE_BRANDS = {
  Car: [
    "Maruti",
    "Hyundai",
    "Honda",
    "Tata",
    "Mahindra",
    "Renault",
    "Toyota",
    "Ford",
    "Nissan",
    "Datsun",
    "Volkswagen",
    "Skoda",
    "Fiat",
    "Isuzu",
    "MG",
    "Kia",
    "Audi",
    "Mercedes-Benz",
    "BMW",
    "Jaguar",
    "Volvo",
    "Lexus",
    "Land Rover",
    "Porsche",
    "Ferrari",
    "Rolls-Royce",
    "Bentley",
    "DC",
    "Force",
    "ICML",
    "Mitsubishi",
    "Lamborghini",
    "Mini",
    "Aston Martin",
    "Maserati",
    "Premier",
    "Mahindra Renault",
    "Chevrolet",
    "Jeep",
    "Caterham",
    "Hindustan Motors",
    "San Motors",
    "Opel",
    "Mahindra SsangYong",
    "Bajaj",
    "Ashok Leyland",
    "Dodge",
    "Tesla",
    "Citroen",
    "Strom Motors",
    "BYD",
    "Mahindra XUV",
    "Mahindra BE",
    "PMV",
    "Vayve Mobility",
  ],
  Bike: [
    "Hero",
    "Honda",
    "Royal Enfield",
    "TVS",
    "Bajaj",
    "Yamaha",
    "Suzuki",
    "KTM",
    "Jawa",
    "Revolt Motors",
    "Mahindra",
    "Vespa",
    "Harley Davidson",
    "Ducati",
    "Kawasaki",
    "Benelli",
    "Hero Electric",
    "Hyosung",
    "Triumph",
    "Indian",
    "BMW",
    "Aprilia",
    "MV Agusta",
    "Avon",
    "Indus",
    "Moto Guzzi",
    "YUKIE",
    "Yezdi Motorcycles",
    "Raftaar",
    "Ujaas Energy",
    "Techo Electra",
    "Benling India",
    "EVOLET",
    "EeVe",
    "Ultraviolette",
    "Evoke Motors",
    "BattRE Electric",
    "Piaggio",
    "Norton",
    "SWM",
    "Emflux Motors",
    "Aftek Motors",
    "FB Mondial",
    "Komaki",
    "CFMoto",
    "Avan Motors",
    "Cleveland CycleWerks",
    "BMW Motorrad",
    "LML",
    "Regal Raptor",
    "Victory",
    "Hero MotoCorp",
  ],
  Truck: [
    "Ashok Leyland",
    "Tata",
    "Mahindra",
    "Eicher",
    "BharatBenz",
    "Volvo",
    "SML Isuzu",
    "Scania",
    "AMW",
  ],
};
const VEHICLE_MODELS = {
  Car: {
    Maruti: ["Swift", "Baleno", "Dzire", "Brezza", "Ertiga", "Wagon R"],
    Hyundai: ["i20", "i10", "Creta", "Venue", "Verna", "Exter"],
    Honda: ["City", "Amaze", "Elevate", "Jazz"],
    Tata: ["Altroz", "Nexon", "Punch", "Harrier", "Tiago"],
    Mahindra: ["XUV 3XO", "XUV700", "Scorpio-N", "Thar"],
    Toyota: ["Glanza", "Urban Cruiser Hyryder", "Innova Crysta", "Fortuner"],
    Kia: ["Seltos", "Sonet", "Carens"],
    Volkswagen: ["Polo", "Virtus", "Taigun", "Tiguan"],
    Skoda: ["Slavia", "Kushaq", "Kodiaq"],
    BMW: ["3 Series", "5 Series", "X1", "X3"],
    Audi: ["A4", "Q3", "Q5"],
    "Mercedes-Benz": ["A-Class", "C-Class", "E-Class", "GLC"],
  },
  Bike: {
    Hero: ["Splendor Plus", "HF Deluxe", "Xtreme 125R", "Karizma"],
    Honda: ["Shine", "SP 125", "Hornet 2.0", "Activa"],
    "Royal Enfield": ["Classic 350", "Hunter 350", "Meteor 350", "Himalayan"],
    TVS: ["Apache RTR 160", "Raider", "Jupiter", "Ntorq"],
    Bajaj: ["Pulsar 150", "Pulsar NS200", "Platina", "Avenger"],
    Yamaha: ["R15", "MT-15", "FZ", "Fascino"],
    Suzuki: ["Gixxer", "Access 125", "V-Strom SX"],
    KTM: ["Duke 200", "Duke 390", "RC 200"],
    Jawa: ["Jawa 42", "Perak"],
    BMW: ["G 310 R", "G 310 GS"],
    Aprilia: ["RS 457", "SR 160"],
    Vespa: ["VXL 125", "SXL 150"],
  },
  SUV: {
    Mahindra: ["XUV 3XO", "XUV700", "Scorpio-N", "Thar"],
    Hyundai: ["Creta", "Alcazar", "Tucson"],
    Kia: ["Seltos", "Sonet", "Carens"],
    Tata: ["Nexon", "Harrier", "Safari"],
    Toyota: ["Fortuner", "Urban Cruiser Hyryder"],
    Jeep: ["Compass", "Meridian", "Wrangler"],
    MG: ["Astor", "Hector", "Gloster"],
    Volkswagen: ["Taigun", "Tiguan"],
    Skoda: ["Kushaq", "Kodiaq"],
  },
  Commercial: {
    "Ashok Leyland": ["Dost", "Partner", "Boss", "Ecomet"],
    Tata: ["Ace", "407", "Ultra", "Prima"],
    Mahindra: ["Bolero Pickup", "Furio", "Blazo"],
    Eicher: ["Pro 2055", "Pro 3015"],
    BharatBenz: ["1217R", "2823R"],
    Volvo: ["FM", "FH"],
  },
};
const VEHICLE_SEGMENTS = {
  Car: ["Hatchback", "Sedan", "MUV", "Premium"],
  Bike: ["Commuter", "Sports", "Cruiser", "Scooter", "Electric"],
  SUV: ["Compact SUV", "Mid-size SUV", "Premium SUV", "4x4"],
  Commercial: ["Light Truck", "Medium Truck", "Heavy Truck", "Bus"],
};

const products = [
  {
    id: 1,
    image: "assets/products/jk-jet-power-100.png",
    brand: "JK",
    name: "JET POWER 100",
    size: "10.00-20",
    vehicle: "Commercial",
    type: "Truck",
    price: null,
    rating: 0,
    reviews: 0,
    tubeless: false,
    wet: "High",
    fuel: "Efficient",
    new: true,
  },
  {
    id: 2,
    image: "assets/products/mrf-steel-muscle-295.png",
    brand: "MRF",
    name: "STEEL MUSCLE 295/90R20",
    size: "295/90R20",
    vehicle: "Commercial",
    type: "Truck",
    price: 24150,
    rating: 4.6,
    reviews: 14,
    tubeless: false,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 3,
    image: "assets/products/mrf-steel-muscle-1100.png",
    brand: "MRF",
    name: "STEEL MUSCLE 11.00R20",
    size: "11.00 R20",
    vehicle: "Commercial",
    type: "Truck",
    price: 55450,
    rating: 4.5,
    reviews: 9,
    tubeless: false,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 4,
    image: "assets/products/mrf-masseter-x.png",
    brand: "MRF",
    name: "Masseter-X",
    size: "100/90-17 55P",
    vehicle: "Bike",
    type: "Bike",
    price: 2545,
    rating: 4.4,
    reviews: 2,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 5,
    image: "assets/products/bkt-thyros-street.png",
    brand: "BKT",
    name: "THYROS STREET",
    size: "90/100-10",
    vehicle: "Bike",
    type: "Scooter",
    price: null,
    rating: 0,
    reviews: 0,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 6,
    image: "assets/products/mrf-zapper.png",
    brand: "MRF",
    name: "ZAPPER (Scooter)",
    size: "90/100 R10",
    vehicle: "Bike",
    type: "Bike",
    price: 1050,
    rating: 4.3,
    reviews: 3,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 7,
    image: "assets/products/ceat-crossdrive-at.png",
    brand: "CEAT",
    name: "CrossDrive AT",
    size: "285/60R18 116/S",
    vehicle: "SUV",
    type: "Car",
    price: 14395,
    rating: 5,
    reviews: 2,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 8,
    image: "assets/products/ceat-securadrive.png",
    brand: "CEAT",
    name: "SecuraDrive",
    size: "185/70R15 89H",
    vehicle: "Car",
    type: "Car",
    price: 6650,
    rating: 4.4,
    reviews: 27,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 9,
    image: "assets/products/ceat-securadrive-suv.png",
    brand: "CEAT",
    name: "SecuraDrive SUV",
    size: "205/65R16 95/H",
    vehicle: "SUV",
    type: "Car",
    price: 8150,
    rating: 5,
    reviews: 8,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 10,
    brand: "Apollo",
    name: "Amazer 4G Life",
    size: "165/80 R14",
    vehicle: "Car",
    type: "Car",
    price: 5350,
    rating: 4.6,
    reviews: 31,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 11,
    brand: "Michelin",
    name: "Energy XM2+",
    size: "195/55 R16",
    vehicle: "Car",
    type: "Car",
    price: 8250,
    rating: 4.8,
    reviews: 44,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 12,
    brand: "Goodyear",
    name: "Assurance TripleMax 2",
    size: "205/55 R16",
    vehicle: "Car",
    type: "Car",
    price: 7600,
    rating: 4.7,
    reviews: 28,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 13,
    brand: "Bridgestone",
    name: "Ecopia EP150",
    size: "185/65 R15",
    vehicle: "Car",
    type: "Car",
    price: 7200,
    rating: 4.5,
    reviews: 18,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 14,
    brand: "Yokohama",
    name: "Earth-1 E400",
    size: "195/65 R15",
    vehicle: "Car",
    type: "Car",
    price: 6950,
    rating: 4.6,
    reviews: 22,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 15,
    brand: "JK",
    name: "Tyre Sport",
    size: "195/60 R15",
    vehicle: "Car",
    type: "Car",
    price: 4850,
    rating: 4.2,
    reviews: 11,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 16,
    brand: "BKT",
    name: "City Pro",
    size: "90/90-12",
    vehicle: "Bike",
    type: "Scooter",
    price: 1180,
    rating: 4.1,
    reviews: 7,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
];

products.push(
  {
    id: 17,
    image: "assets/products/ceat-securadrive.png",
    brand: "CEAT",
    name: "SecuraDrive 185/65R15",
    size: "185/65 R15",
    vehicle: "Car",
    type: "Car",
    segment: "Sedan",
    model: "Swift",
    vehicleBrand: "Maruti",
    price: 6850,
    rating: 4.5,
    reviews: 19,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 18,
    image: "assets/products/ceat-securadrive-suv.png",
    brand: "CEAT",
    name: "SecuraDrive SUV 215/60R17",
    size: "215/60 R17",
    vehicle: "SUV",
    type: "Car",
    segment: "Mid-size SUV",
    model: "Creta",
    vehicleBrand: "Hyundai",
    price: 9250,
    rating: 4.7,
    reviews: 16,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 19,
    image: "assets/products/ceat-crossdrive-at.png",
    brand: "CEAT",
    name: "CrossDrive AT 265/65R17",
    size: "265/65 R17",
    vehicle: "SUV",
    type: "Car",
    segment: "4x4",
    model: "Fortuner",
    vehicleBrand: "Toyota",
    price: 15890,
    rating: 4.8,
    reviews: 12,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 20,
    image: "assets/products/mrf-masseter-x.png",
    brand: "MRF",
    name: "Masseter-X 90/90-17",
    size: "90/90-17 49P",
    vehicle: "Bike",
    type: "Bike",
    segment: "Commuter",
    model: "Splendor Plus",
    vehicleBrand: "Hero",
    price: 2380,
    rating: 4.5,
    reviews: 13,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 21,
    image: "assets/products/mrf-zapper.png",
    brand: "MRF",
    name: "ZAPPER 100/90-17",
    size: "100/90 R17",
    vehicle: "Bike",
    type: "Bike",
    segment: "Sports",
    model: "Pulsar 150",
    vehicleBrand: "Bajaj",
    price: 1420,
    rating: 4.4,
    reviews: 10,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 22,
    image: "assets/products/bkt-thyros-street.png",
    brand: "BKT",
    name: "THYROS STREET 90/90-12",
    size: "90/90-12",
    vehicle: "Bike",
    type: "Scooter",
    segment: "Scooter",
    model: "Activa",
    vehicleBrand: "Honda",
    price: 1190,
    rating: 4.2,
    reviews: 8,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 23,
    image: "assets/products/mrf-steel-muscle-295.png",
    brand: "MRF",
    name: "STEEL MUSCLE 10.00R20",
    size: "10.00R20",
    vehicle: "Commercial",
    type: "Truck",
    segment: "Medium Truck",
    model: "407",
    vehicleBrand: "Tata",
    price: 24250,
    rating: 4.5,
    reviews: 7,
    tubeless: false,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 24,
    image: "assets/products/mrf-steel-muscle-1100.png",
    brand: "MRF",
    name: "STEEL MUSCLE 12.00R20",
    size: "12.00R20",
    vehicle: "Commercial",
    type: "Truck",
    segment: "Heavy Truck",
    model: "Prima",
    vehicleBrand: "Tata",
    price: 61200,
    rating: 4.6,
    reviews: 6,
    tubeless: false,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 25,
    image: "assets/products/jk-jet-power-100.png",
    brand: "JK",
    name: "JET POWER 100 9.00R20",
    size: "9.00R20",
    vehicle: "Commercial",
    type: "Truck",
    segment: "Light Truck",
    model: "Dost",
    vehicleBrand: "Ashok Leyland",
    price: 21400,
    rating: 4.2,
    reviews: 5,
    tubeless: false,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 26,
    image: "assets/products/ceat-securadrive.png",
    brand: "CEAT",
    name: "SecuraDrive 195/60R15",
    size: "195/60 R15",
    vehicle: "Car",
    type: "Car",
    segment: "Hatchback",
    model: "Baleno",
    vehicleBrand: "Maruti",
    price: 6450,
    rating: 4.4,
    reviews: 24,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 27,
    image: "assets/products/ceat-securadrive.png",
    brand: "CEAT",
    name: "SecuraDrive 195/65R15",
    size: "195/65 R15",
    vehicle: "Car",
    type: "Car",
    segment: "Sedan",
    model: "City",
    vehicleBrand: "Honda",
    price: 6990,
    rating: 4.6,
    reviews: 21,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 28,
    image: "assets/products/ceat-crossdrive-at.png",
    brand: "CEAT",
    name: "CrossDrive AT 235/70R16",
    size: "235/70 R16",
    vehicle: "SUV",
    type: "Car",
    segment: "4x4",
    model: "Scorpio-N",
    vehicleBrand: "Mahindra",
    price: 13750,
    rating: 4.6,
    reviews: 15,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 29,
    image: "assets/products/mrf-masseter-x.png",
    brand: "MRF",
    name: "Masseter-X 100/90-17",
    size: "100/90-17 55P",
    vehicle: "Bike",
    type: "Bike",
    segment: "Commuter",
    model: "Shine",
    vehicleBrand: "Honda",
    price: 2520,
    rating: 4.4,
    reviews: 11,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 30,
    image: "assets/products/mrf-zapper.png",
    brand: "MRF",
    name: "ZAPPER 90/90-18",
    size: "90/90 R18",
    vehicle: "Bike",
    type: "Bike",
    segment: "Commuter",
    model: "Classic 350",
    vehicleBrand: "Royal Enfield",
    price: 1550,
    rating: 4.3,
    reviews: 9,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
);

const DEFAULT_VEHICLE_BRANDS = {
  1: "Ashok Leyland",
  2: "Tata",
  3: "Tata",
  4: "Hero",
  5: "Honda",
  6: "TVS",
  7: "Toyota",
  8: "Maruti",
  9: "Hyundai",
  10: "Maruti",
  11: "Hyundai",
  12: "Toyota",
  13: "Tata",
  14: "Honda",
  15: "Mahindra",
  16: "TVS",
};
products.forEach((p) => {
  if (!p.vehicleBrand && DEFAULT_VEHICLE_BRANDS[p.id])
    p.vehicleBrand = DEFAULT_VEHICLE_BRANDS[p.id];
});

products.push(
  {
    id: 31,
    image: "assets/products/ref-carreal-1.jpg",
    brand: "Yokohama",
    name: "BluEarth-GT AE51",
    size: "225/55 R17",
    vehicle: "Car",
    type: "Car",
    segment: "Sedan",
    model: "City",
    vehicleBrand: "Honda",
    price: 12378,
    rating: 4.5,
    reviews: 38,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 32,
    image: "assets/products/ref-carreal-2.jpg",
    brand: "Apollo",
    name: "Apterra H/P",
    size: "235/60 R18",
    vehicle: "SUV",
    type: "Car",
    segment: "Premium SUV",
    model: "XUV700",
    vehicleBrand: "Mahindra",
    price: 14400,
    rating: 4.6,
    reviews: 25,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 33,
    image: "assets/products/ceat-securadrive.png",
    brand: "Continental",
    name: "UC6",
    size: "215/55 R17",
    vehicle: "Car",
    type: "Car",
    segment: "Sedan",
    model: "Virtus",
    vehicleBrand: "Volkswagen",
    price: 11150,
    rating: 4.3,
    reviews: 31,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 34,
    image: "assets/products/ceat-securadrive.png",
    brand: "CEAT",
    name: "SecuraDrive 85S",
    size: "165/80 R14",
    vehicle: "Car",
    type: "Car",
    segment: "Hatchback",
    model: "Swift",
    vehicleBrand: "Maruti",
    price: 4499,
    rating: 4.5,
    reviews: 346,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 35,
    image: "assets/products/ceat-crossdrive-at.png",
    brand: "MRF",
    name: "Perfinza CLX1",
    size: "195/65 R15",
    vehicle: "Car",
    type: "Car",
    segment: "Sedan",
    model: "Verna",
    vehicleBrand: "Hyundai",
    price: 7523,
    rating: 4.4,
    reviews: 41,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 36,
    image: "assets/products/ceat-crossdrive-at.png",
    brand: "Yokohama",
    name: "Geolandar A/T",
    size: "265/65 R17",
    vehicle: "SUV",
    type: "Car",
    segment: "4x4",
    model: "Fortuner",
    vehicleBrand: "Toyota",
    price: 16450,
    rating: 4.7,
    reviews: 29,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 37,
    image: "assets/products/ceat-securadrive-suv.png",
    brand: "Apollo",
    name: "Aspire 4G+",
    size: "205/55 R16",
    vehicle: "Car",
    type: "Car",
    segment: "Sedan",
    model: "Slavia",
    vehicleBrand: "Skoda",
    price: 7820,
    rating: 4.5,
    reviews: 47,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 38,
    image: "assets/products/ceat-securadrive.png",
    brand: "Bridgestone",
    name: "Turanza T001",
    size: "185/65 R15",
    vehicle: "Car",
    type: "Car",
    segment: "Sedan",
    model: "Dzire",
    vehicleBrand: "Maruti",
    price: 6890,
    rating: 4.6,
    reviews: 52,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 39,
    image: "assets/products/ceat-securadrive.png",
    brand: "Goodyear",
    name: "Assurance TripleMax",
    size: "195/55 R16",
    vehicle: "Car",
    type: "Car",
    segment: "Hatchback",
    model: "i20",
    vehicleBrand: "Hyundai",
    price: 7350,
    rating: 4.5,
    reviews: 33,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 40,
    image: "assets/products/ceat-securadrive.png",
    brand: "Michelin",
    name: "Primacy 4",
    size: "205/60 R16",
    vehicle: "Car",
    type: "Car",
    segment: "Sedan",
    model: "City",
    vehicleBrand: "Honda",
    price: 10190,
    rating: 4.8,
    reviews: 68,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 41,
    image: "assets/products/ceat-securadrive.png",
    brand: "Pirelli",
    name: "Cinturato P7",
    size: "225/45 R17",
    vehicle: "Car",
    type: "Car",
    segment: "Premium",
    model: "3 Series",
    vehicleBrand: "BMW",
    price: 15990,
    rating: 4.7,
    reviews: 22,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 42,
    image: "assets/products/ceat-securadrive.png",
    brand: "Continental",
    name: "ContiSportContact 5",
    size: "225/50 R17",
    vehicle: "Car",
    type: "Car",
    segment: "Premium",
    model: "A4",
    vehicleBrand: "Audi",
    price: 15100,
    rating: 4.7,
    reviews: 18,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 43,
    image: "assets/products/ceat-securadrive-suv.png",
    brand: "CEAT",
    name: "Milaze",
    size: "175/65 R14",
    vehicle: "Car",
    type: "Car",
    segment: "Hatchback",
    model: "Baleno",
    vehicleBrand: "Maruti",
    price: 5190,
    rating: 4.2,
    reviews: 39,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 44,
    image: "assets/products/ceat-securadrive.png",
    brand: "JK",
    name: "UX Royale",
    size: "185/65 R15",
    vehicle: "Car",
    type: "Car",
    segment: "Sedan",
    model: "Amaze",
    vehicleBrand: "Honda",
    price: 5520,
    rating: 4.2,
    reviews: 17,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 45,
    image: "assets/products/ceat-securadrive.png",
    brand: "Birla",
    name: "Vredestein Centauro",
    size: "195/65 R15",
    vehicle: "Car",
    type: "Car",
    segment: "Sedan",
    model: "Nexon",
    vehicleBrand: "Tata",
    price: 6350,
    rating: 4.3,
    reviews: 14,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 46,
    image: "assets/products/ceat-crossdrive-at.png",
    brand: "Michelin",
    name: "Latitude Sport 3",
    size: "235/55 R19",
    vehicle: "SUV",
    type: "Car",
    segment: "Premium SUV",
    model: "GLC",
    vehicleBrand: "Mercedes-Benz",
    price: 22100,
    rating: 4.8,
    reviews: 19,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 47,
    image: "assets/products/ceat-crossdrive-at.png",
    brand: "Goodyear",
    name: "Wrangler AT Adventure",
    size: "265/60 R18",
    vehicle: "SUV",
    type: "Car",
    segment: "4x4",
    model: "Fortuner",
    vehicleBrand: "Toyota",
    price: 17400,
    rating: 4.6,
    reviews: 27,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 48,
    image: "assets/products/ceat-securadrive-suv.png",
    brand: "Bridgestone",
    name: "Dueler H/P Sport",
    size: "255/55 R19",
    vehicle: "SUV",
    type: "Car",
    segment: "Premium SUV",
    model: "Q5",
    vehicleBrand: "Audi",
    price: 20800,
    rating: 4.7,
    reviews: 16,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 49,
    image: "assets/products/ceat-crossdrive-at.png",
    brand: "Yokohama",
    name: "Geolandar G055",
    size: "225/65 R17",
    vehicle: "SUV",
    type: "Car",
    segment: "Mid-size SUV",
    model: "Creta",
    vehicleBrand: "Hyundai",
    price: 10990,
    rating: 4.6,
    reviews: 34,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 50,
    image: "assets/products/ceat-securadrive-suv.png",
    brand: "Apollo",
    name: "Apterra HP",
    size: "215/60 R17",
    vehicle: "SUV",
    type: "Car",
    segment: "Mid-size SUV",
    model: "Seltos",
    vehicleBrand: "Kia",
    price: 9980,
    rating: 4.5,
    reviews: 28,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 51,
    image: "assets/products/ceat-crossdrive-at.png",
    brand: "CEAT",
    name: "CrossDrive AT Plus",
    size: "245/70 R16",
    vehicle: "SUV",
    type: "Car",
    segment: "4x4",
    model: "Thar",
    vehicleBrand: "Mahindra",
    price: 12850,
    rating: 4.6,
    reviews: 21,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 52,
    image: "assets/products/ceat-securadrive-suv.png",
    brand: "MRF",
    name: "Wanderer",
    size: "215/65 R16",
    vehicle: "SUV",
    type: "Car",
    segment: "Mid-size SUV",
    model: "Scorpio-N",
    vehicleBrand: "Mahindra",
    price: 10650,
    rating: 4.4,
    reviews: 23,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 53,
    image: "assets/products/ceat-crossdrive-at.png",
    brand: "Continental",
    name: "CrossContact LX2",
    size: "235/60 R18",
    vehicle: "SUV",
    type: "Car",
    segment: "Premium SUV",
    model: "Tiguan",
    vehicleBrand: "Volkswagen",
    price: 16990,
    rating: 4.7,
    reviews: 13,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 54,
    image: "assets/products/ceat-securadrive-suv.png",
    brand: "Pirelli",
    name: "Scorpion Verde",
    size: "225/60 R18",
    vehicle: "SUV",
    type: "Car",
    segment: "Premium SUV",
    model: "Kodiaq",
    vehicleBrand: "Skoda",
    price: 18200,
    rating: 4.7,
    reviews: 12,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 55,
    image: "assets/products/ceat-crossdrive-at.png",
    brand: "Goodyear",
    name: "EfficientGrip SUV",
    size: "215/65 R17",
    vehicle: "SUV",
    type: "Car",
    segment: "Mid-size SUV",
    model: "Hector",
    vehicleBrand: "MG",
    price: 11250,
    rating: 4.5,
    reviews: 26,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 56,
    image: "assets/products/ceat-securadrive.png",
    brand: "CEAT",
    name: "SecuraDrive 195/60R15",
    size: "195/60 R15",
    vehicle: "Car",
    type: "Car",
    segment: "Hatchback",
    model: "i20",
    vehicleBrand: "Hyundai",
    price: 6420,
    rating: 4.4,
    reviews: 37,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 57,
    image: "assets/products/ceat-securadrive.png",
    brand: "MRF",
    name: "ZLX 175/65R15",
    size: "175/65 R15",
    vehicle: "Car",
    type: "Car",
    segment: "Hatchback",
    model: "Baleno",
    vehicleBrand: "Maruti",
    price: 6100,
    rating: 4.3,
    reviews: 20,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 58,
    image: "assets/products/ceat-securadrive.png",
    brand: "Apollo",
    name: "Amazer 4G Life 185",
    size: "185/65 R15",
    vehicle: "Car",
    type: "Car",
    segment: "Sedan",
    model: "Amaze",
    vehicleBrand: "Honda",
    price: 5650,
    rating: 4.5,
    reviews: 44,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 59,
    image: "assets/products/ceat-securadrive.png",
    brand: "Bridgestone",
    name: "Ecopia EP150 195",
    size: "195/65 R15",
    vehicle: "Car",
    type: "Car",
    segment: "Sedan",
    model: "Verna",
    vehicleBrand: "Hyundai",
    price: 7550,
    rating: 4.5,
    reviews: 32,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 60,
    image: "assets/products/ceat-securadrive.png",
    brand: "Yokohama",
    name: "Earth-1 185",
    size: "185/65 R15",
    vehicle: "Car",
    type: "Car",
    segment: "Sedan",
    model: "Virtus",
    vehicleBrand: "Volkswagen",
    price: 7050,
    rating: 4.6,
    reviews: 29,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 61,
    image: "assets/products/ref-bikereal-1.jpg",
    brand: "Pirelli",
    name: "Diablo Rosso",
    size: "120/70 ZR17",
    vehicle: "Bike",
    type: "Bike",
    segment: "Sports",
    model: "Duke 390",
    vehicleBrand: "KTM",
    price: 34500,
    rating: 4.8,
    reviews: 591,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 62,
    image: "assets/products/ref-bikereal-1.jpg",
    brand: "Eurogrip",
    name: "Remora",
    size: "100/80-12 56J",
    vehicle: "Bike",
    type: "Scooter",
    segment: "Scooter",
    model: "Activa",
    vehicleBrand: "Honda",
    price: 1958,
    rating: 4.4,
    reviews: 87,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 63,
    image: "assets/products/ref-bikereal-1.jpg",
    brand: "Michelin",
    name: "Pilot Street 2",
    size: "80/100-18 54P",
    vehicle: "Bike",
    type: "Bike",
    segment: "Commuter",
    model: "Shine",
    vehicleBrand: "Honda",
    price: 2599,
    rating: 4.8,
    reviews: 4700,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 64,
    image: "assets/products/mrf-masseter-x.png",
    brand: "Apollo",
    name: "Alpha H1 Rear",
    size: "110/70 ZR17",
    vehicle: "Bike",
    type: "Bike",
    segment: "Sports",
    model: "Apache RTR 160",
    vehicleBrand: "TVS",
    price: 4600,
    rating: 4.6,
    reviews: 16,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 65,
    image: "assets/products/mrf-zapper.png",
    brand: "CEAT",
    name: "Gripp CRUZ",
    size: "120/80-16 60P",
    vehicle: "Bike",
    type: "Bike",
    segment: "Commuter",
    model: "Pulsar 150",
    vehicleBrand: "Bajaj",
    price: 16044,
    rating: 4.4,
    reviews: 23,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 66,
    image: "assets/products/ref-bikereal-1.jpg",
    brand: "Michelin",
    name: "Pilot Street 2 IN",
    size: "100/90-17 55P",
    vehicle: "Bike",
    type: "Bike",
    segment: "Commuter",
    model: "Classic 350",
    vehicleBrand: "Royal Enfield",
    price: 3521,
    rating: 4.5,
    reviews: 42,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 67,
    image: "assets/products/mrf-masseter-x.png",
    brand: "CEAT",
    name: "Zoom 100/90-17",
    size: "100/90-17",
    vehicle: "Bike",
    type: "Bike",
    segment: "Sports",
    model: "R15",
    vehicleBrand: "Yamaha",
    price: 2377,
    rating: 4.9,
    reviews: 18,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 68,
    image: "assets/products/mrf-zapper.png",
    brand: "MRF",
    name: "Zapper FS",
    size: "90/90-18",
    vehicle: "Bike",
    type: "Bike",
    segment: "Commuter",
    model: "Splendor Plus",
    vehicleBrand: "Hero",
    price: 1450,
    rating: 4.4,
    reviews: 31,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 69,
    image: "assets/products/mrf-masseter-x.png",
    brand: "Goodyear",
    name: "Eagle Sport Motorcycle",
    size: "100/80-17",
    vehicle: "Bike",
    type: "Bike",
    segment: "Sports",
    model: "MT-15",
    vehicleBrand: "Yamaha",
    price: 2890,
    rating: 4.5,
    reviews: 20,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 70,
    image: "assets/products/bkt-thyros-street.png",
    brand: "Kenda",
    name: "K262",
    size: "90/90-12",
    vehicle: "Bike",
    type: "Scooter",
    segment: "Scooter",
    model: "Jupiter",
    vehicleBrand: "TVS",
    price: 1690,
    rating: 4.2,
    reviews: 12,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 71,
    image: "assets/products/mrf-zapper.png",
    brand: "Ralco",
    name: "Speed Blaster",
    size: "90/90-17",
    vehicle: "Bike",
    type: "Bike",
    segment: "Commuter",
    model: "Shine",
    vehicleBrand: "Honda",
    price: 1380,
    rating: 4.1,
    reviews: 9,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 72,
    image: "assets/products/mrf-masseter-x.png",
    brand: "Metzeler",
    name: "Sportec M7 RR",
    size: "120/70 ZR17",
    vehicle: "Bike",
    type: "Bike",
    segment: "Sports",
    model: "Duke 390",
    vehicleBrand: "KTM",
    price: 12900,
    rating: 4.7,
    reviews: 14,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 73,
    image: "assets/products/mrf-zapper.png",
    brand: "TVS",
    name: "Eurogrip Duratrail",
    size: "100/90-18",
    vehicle: "Bike",
    type: "Bike",
    segment: "Cruiser",
    model: "Hunter 350",
    vehicleBrand: "Royal Enfield",
    price: 2250,
    rating: 4.4,
    reviews: 17,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 74,
    image: "assets/products/bkt-thyros-street.png",
    brand: "BKT",
    name: "Scooter Pro",
    size: "90/90-12",
    vehicle: "Bike",
    type: "Scooter",
    segment: "Scooter",
    model: "Access 125",
    vehicleBrand: "Suzuki",
    price: 1195,
    rating: 4.3,
    reviews: 15,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 75,
    image: "assets/products/mrf-masseter-x.png",
    brand: "Michelin",
    name: "Pilot Street Radial",
    size: "110/70-17",
    vehicle: "Bike",
    type: "Bike",
    segment: "Sports",
    model: "Apache RTR 160",
    vehicleBrand: "TVS",
    price: 4250,
    rating: 4.7,
    reviews: 35,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 76,
    image: "assets/products/mrf-steel-muscle-295.png",
    brand: "Goodyear",
    name: "Giti Commercial 295",
    size: "295/80R22.5",
    vehicle: "Commercial",
    type: "Truck",
    segment: "Heavy Truck",
    model: "FM",
    vehicleBrand: "Volvo",
    price: 48500,
    rating: 4.5,
    reviews: 8,
    tubeless: false,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 77,
    image: "assets/products/mrf-steel-muscle-1100.png",
    brand: "Bridgestone",
    name: "M729",
    size: "11.00R20",
    vehicle: "Commercial",
    type: "Truck",
    segment: "Heavy Truck",
    model: "Prima",
    vehicleBrand: "Tata",
    price: 55800,
    rating: 4.6,
    reviews: 11,
    tubeless: false,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 78,
    image: "assets/products/jk-jet-power-100.png",
    brand: "JK",
    name: "Jet Ribo",
    size: "10.00R20",
    vehicle: "Commercial",
    type: "Truck",
    segment: "Medium Truck",
    model: "407",
    vehicleBrand: "Tata",
    price: 26800,
    rating: 4.4,
    reviews: 7,
    tubeless: false,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 79,
    image: "assets/products/mrf-steel-muscle-295.png",
    brand: "Apollo",
    name: "EnduRace RA",
    size: "295/90R20",
    vehicle: "Commercial",
    type: "Truck",
    segment: "Heavy Truck",
    model: "Boss",
    vehicleBrand: "Ashok Leyland",
    price: 29900,
    rating: 4.3,
    reviews: 6,
    tubeless: false,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 80,
    image: "assets/products/mrf-steel-muscle-1100.png",
    brand: "CEAT",
    name: "Winmile X3",
    size: "10.00R20",
    vehicle: "Commercial",
    type: "Truck",
    segment: "Medium Truck",
    model: "Ultra",
    vehicleBrand: "Tata",
    price: 28400,
    rating: 4.4,
    reviews: 5,
    tubeless: false,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 81,
    image: "assets/products/jk-jet-power-100.png",
    brand: "MRF",
    name: "Steel Muscle 9.00R20",
    size: "9.00R20",
    vehicle: "Commercial",
    type: "Truck",
    segment: "Light Truck",
    model: "Dost",
    vehicleBrand: "Ashok Leyland",
    price: 22900,
    rating: 4.5,
    reviews: 12,
    tubeless: false,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 82,
    image: "assets/products/mrf-steel-muscle-295.png",
    brand: "JK",
    name: "Jet Steel 12.00R20",
    size: "12.00R20",
    vehicle: "Commercial",
    type: "Truck",
    segment: "Heavy Truck",
    model: "FH",
    vehicleBrand: "Volvo",
    price: 61200,
    rating: 4.6,
    reviews: 9,
    tubeless: false,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 83,
    image: "assets/products/mrf-steel-muscle-295.png",
    brand: "BKT",
    name: "FleetMaster",
    size: "10.00R20",
    vehicle: "Commercial",
    type: "Truck",
    segment: "Medium Truck",
    model: "Pro 2055",
    vehicleBrand: "Eicher",
    price: 27600,
    rating: 4.2,
    reviews: 5,
    tubeless: false,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 84,
    image: "assets/products/mrf-steel-muscle-1100.png",
    brand: "Michelin",
    name: "X Multi Z2",
    size: "295/80R22.5",
    vehicle: "Commercial",
    type: "Truck",
    segment: "Heavy Truck",
    model: "2823R",
    vehicleBrand: "BharatBenz",
    price: 52500,
    rating: 4.7,
    reviews: 10,
    tubeless: false,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 85,
    image: "assets/products/jk-jet-power-100.png",
    brand: "Goodyear",
    name: "Unisteel G159",
    size: "10.00R20",
    vehicle: "Commercial",
    type: "Truck",
    segment: "Medium Truck",
    model: "Partner",
    vehicleBrand: "Ashok Leyland",
    price: 30100,
    rating: 4.3,
    reviews: 4,
    tubeless: false,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 86,
    image: "assets/products/mrf-steel-muscle-1100.png",
    brand: "Continental",
    name: "Conti Hybrid HD3",
    size: "11.00R20",
    vehicle: "Commercial",
    type: "Truck",
    segment: "Heavy Truck",
    model: "Pro 3015",
    vehicleBrand: "Eicher",
    price: 46700,
    rating: 4.5,
    reviews: 7,
    tubeless: false,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 87,
    image: "assets/products/ceat-securadrive.png",
    brand: "MRF",
    name: "Perfinza CLX1 205",
    size: "205/55 R16",
    vehicle: "Car",
    type: "Car",
    segment: "Sedan",
    model: "Virtus",
    vehicleBrand: "Volkswagen",
    price: 7820,
    rating: 4.4,
    reviews: 27,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 88,
    image: "assets/products/ceat-securadrive.png",
    brand: "Michelin",
    name: "Energy XM2+ 185",
    size: "185/65 R15",
    vehicle: "Car",
    type: "Car",
    segment: "Hatchback",
    model: "Swift",
    vehicleBrand: "Maruti",
    price: 8050,
    rating: 4.8,
    reviews: 51,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 89,
    image: "assets/products/ceat-crossdrive-at.png",
    brand: "Bridgestone",
    name: "Turanza ER60",
    size: "195/55 R16",
    vehicle: "Car",
    type: "Car",
    segment: "Sedan",
    model: "City",
    vehicleBrand: "Honda",
    price: 8450,
    rating: 4.6,
    reviews: 36,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 90,
    image: "assets/products/ceat-securadrive-suv.png",
    brand: "Yokohama",
    name: "BluEarth AE51",
    size: "205/60 R16",
    vehicle: "Car",
    type: "Car",
    segment: "Sedan",
    model: "Creta",
    vehicleBrand: "Hyundai",
    price: 8790,
    rating: 4.7,
    reviews: 42,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 91,
    image: "assets/products/ceat-crossdrive-at.png",
    brand: "Goodyear",
    name: "Assurance Duraplus 2",
    size: "175/65 R15",
    vehicle: "Car",
    type: "Car",
    segment: "Hatchback",
    model: "Baleno",
    vehicleBrand: "Maruti",
    price: 5890,
    rating: 4.4,
    reviews: 63,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 92,
    image: "assets/products/ceat-securadrive.png",
    brand: "Apollo",
    name: "Amazer 4G Life 195",
    size: "195/65 R15",
    vehicle: "Car",
    type: "Car",
    segment: "Sedan",
    model: "Verna",
    vehicleBrand: "Hyundai",
    price: 6150,
    rating: 4.5,
    reviews: 58,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 93,
    image: "assets/products/ceat-securadrive-suv.png",
    brand: "CEAT",
    name: "SecuraDrive 205",
    size: "205/65 R16",
    vehicle: "SUV",
    type: "Car",
    segment: "Mid-size SUV",
    model: "Nexon",
    vehicleBrand: "Tata",
    price: 8150,
    rating: 4.5,
    reviews: 22,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 94,
    image: "assets/products/ceat-crossdrive-at.png",
    brand: "MRF",
    name: "Wanderer Sport",
    size: "215/65 R16",
    vehicle: "SUV",
    type: "Car",
    segment: "Mid-size SUV",
    model: "Seltos",
    vehicleBrand: "Kia",
    price: 10650,
    rating: 4.5,
    reviews: 19,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 95,
    image: "assets/products/mrf-masseter-x.png",
    brand: "Pirelli",
    name: "Angel ST",
    size: "110/70-17",
    vehicle: "Bike",
    type: "Bike",
    segment: "Sports",
    model: "MT-15",
    vehicleBrand: "Yamaha",
    price: 21600,
    rating: 4.7,
    reviews: 18,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 96,
    image: "assets/products/mrf-zapper.png",
    brand: "MRF",
    name: "Nylogrip Zapper",
    size: "90/90-18",
    vehicle: "Bike",
    type: "Bike",
    segment: "Commuter",
    model: "Splendor Plus",
    vehicleBrand: "Hero",
    price: 1250,
    rating: 4.3,
    reviews: 44,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 97,
    image: "assets/products/mrf-masseter-x.png",
    brand: "CEAT",
    name: "Zoom Plus",
    size: "100/90-17",
    vehicle: "Bike",
    type: "Bike",
    segment: "Sports",
    model: "Pulsar NS200",
    vehicleBrand: "Bajaj",
    price: 2450,
    rating: 4.5,
    reviews: 26,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 98,
    image: "assets/products/bkt-thyros-street.png",
    brand: "Michelin",
    name: "City Pro Scooter",
    size: "90/90-12",
    vehicle: "Bike",
    type: "Scooter",
    segment: "Scooter",
    model: "Access 125",
    vehicleBrand: "Suzuki",
    price: 2890,
    rating: 4.6,
    reviews: 17,
    tubeless: true,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 99,
    image: "assets/products/mrf-steel-muscle-295.png",
    brand: "JK",
    name: "Jet Power HD",
    size: "10.00-20",
    vehicle: "Commercial",
    type: "Truck",
    segment: "Medium Truck",
    model: "407",
    vehicleBrand: "Tata",
    price: 24750,
    rating: 4.3,
    reviews: 8,
    tubeless: false,
    wet: "High",
    fuel: "Efficient",
  },
  {
    id: 100,
    image: "assets/products/mrf-steel-muscle-1100.png",
    brand: "MRF",
    name: "Steel Muscle HD",
    size: "12.00R20",
    vehicle: "Commercial",
    type: "Truck",
    segment: "Heavy Truck",
    model: "Blazo",
    vehicleBrand: "Mahindra",
    price: 58400,
    rating: 4.6,
    reviews: 12,
    tubeless: false,
    wet: "High",
    fuel: "Efficient",
  },
);
